#!/usr/bin/env python3
"""Measure frame-to-frame alpha change for VideoMaMa and VideoMaMa++ and write
`static/js/temporal.js`, the curve the hero section plots under the two players.

Run after adding or replacing clips:
    python3 tools/temporal_stats.py

Needs imageio + numpy (the mp4s are decoded frame by frame).

For every clip and both methods the curve is

    d[t] = mean |alpha[t] - alpha[t-1]|          (0-255 units, t = 1 .. T-1)

so a chunk seam -- a frame where the model restarts its temporal context and the
matte jumps -- shows up as an isolated spike, while genuine motion shows up as a
broad, smooth hump. The page plots both curves on one axis; nothing is
normalised away, so the two methods stay directly comparable.
"""
import json
import os
import sys

import numpy as np

try:
    import imageio.v2 as iio
except ImportError:
    sys.exit("imageio is required: pip install imageio imageio-ffmpeg")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VIDEOS = os.path.join(ROOT, "videos")
JS = os.path.join(ROOT, "static", "js", "temporal.js")

# Left/right of the hero comparison, in that order.
PAIR = ["VideoMaMa", "VideoMaMa++"]

# Every 4th pixel per axis: the curve is a spatial mean, so the subsample tracks
# the full-resolution value closely and keeps 4K clips quick to decode.
STRIDE = 4

HEADER = """/* ==========================================================================
   VideoMaMa++ - frame-to-frame alpha change, per clip
   --------------------------------------------------------------------------
   GENERATED by tools/temporal_stats.py -- do not edit by hand.

   curves[clip][method][t] = mean |alpha[t] - alpha[t-1]| over the whole frame,
   in 0-255 units. Chunk seams read as isolated spikes; motion reads as a broad
   hump. Consumed by static/js/pair.js.
   ========================================================================== */

window.VMPP_TEMPORAL = """


def curve(path):
    # passthrough: one frame per encoded frame. The default re-times to a
    # constant rate and can repeat frames, which reads as fake zero-change steps.
    frames = iio.mimread(path, memtest=False, output_params=["-fps_mode", "passthrough"])
    if not frames:
        return []
    a = np.stack([f[..., 0] if f.ndim == 3 else f for f in frames])
    a = a[:, ::STRIDE, ::STRIDE].astype(np.float32)
    d = np.abs(np.diff(a, axis=0)).mean(axis=(1, 2))
    return [round(float(x), 2) for x in d]


def main():
    if not os.path.isdir(VIDEOS):
        sys.exit(f"no videos/ directory at {VIDEOS}")

    clips = sorted(d for d in os.listdir(VIDEOS) if os.path.isdir(os.path.join(VIDEOS, d)))
    out = {}
    for clip in clips:
        entry = {}
        for method in PAIR:
            path = os.path.join(VIDEOS, clip, method, "pred_alpha.mp4")
            if not os.path.exists(path):
                continue
            entry[method] = curve(path)
            print(f"{clip}/{method}: {len(entry[method])} steps", flush=True)
        if len(entry) == len(PAIR):
            out[clip] = entry

    with open(JS, "w") as fh:
        fh.write(HEADER + json.dumps({"curves": out}, indent=1) + ";\n")
    print(f"\nwrote {JS} ({len(out)} clips)")


if __name__ == "__main__":
    main()
